name: gas-sensing-app
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pyyaml>=6.0
  - pyqt6>=6.4.0
  - pyqtgraph>=0.13.0
  - pyvisa
  - pyserial
  - pymeasure
  - pyvisa-py
  # This block tells Conda to hand the final local installation over to pip
  - pip:
    - -e .